package com.mycompany.mavenproject1;
import java.awt.*;
import static java.lang.Integer.parseInt;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;

public class AdminPanel extends javax.swing.JPanel {
    CardLayout cardLayout;
    private Inventario inventario;
    private ManejoCategorias manejoCategorias;
    private ListaClientes listaClientes;
    
    public AdminPanel(Inventario inventario) {
        this.inventario = inventario;
        this.manejoCategorias = new ManejoCategorias();
        initComponents();
        this.listaClientes = new ListaClientes();
        actualizarTablaClient();
        paneles.setLayout(new java.awt.CardLayout());

        paneles.add(listaPane, "listaPane");
        paneles.add(inventarioPane, "inventarioPane");
        paneles.add(recepcionPane, "recepcionPane");
        paneles.add(categoriasPane, "categoriasPane");
        paneles.add(clientesPane, "clientesPane");
        Component[] components = this.getComponents();
        for(Component component : components){
            if(component instanceof JButton){
                ((JButton) component).setUI(new BasicButtonUI());
                ((JButton) component).setFocusPainted(false);
            }
        }
        cardLayout = (CardLayout)(paneles.getLayout());
    }
    
    public ManejoCategorias getManejoCategorias(){
        return manejoCategorias;
    }
    
    public void actualizarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) tablaLista.getModel();
        modelo.setRowCount(0);
        
        for (Producto p : inventario.getLista()){
            modelo.addRow(new Object[]{
                p.getId(), p.getNombre(), p.getCategoria(), p.getTipo(), p.getPrecio(), p.getStock()
            });
        }
    }
    
    /*public void actualizarTablaInv(){
        DefaultTableModel modelo = (DefaultTableModel) tablaCat.getModel();
        modelo.setRowCount(0);
        List<Categoria> categorias = manejoCategorias.getCategorias();
        for (int i=0 ; i < categorias.size(); i++){
            Categoria c = categorias.get(i);
            modelo.addRow(new Object[]{
                i + 1, c.getNombre()
            });
        }
    }
    
    public void actualizarTablaRecep(){
        DefaultTableModel modelo = (DefaultTableModel) tablaCat.getModel();
        modelo.setRowCount(0);
        List<Categoria> categorias = manejoCategorias.getCategorias();
        for (int i=0 ; i < categorias.size(); i++){
            Categoria c = categorias.get(i);
            modelo.addRow(new Object[]{
                i + 1, c.getNombre()
            });
        }
    }*/
    
    public void actualizarTablaCat(){
        DefaultTableModel modelo = (DefaultTableModel) tablaCat.getModel();
        modelo.setRowCount(0);
        
        for (Categoria p : manejoCategorias.getCategorias()){
            modelo.addRow(new Object[]{
                p.getNombre()
            });
        }
    }
    public void actualizarTablaClient(){
        DefaultTableModel modelo = (DefaultTableModel) tablaClient.getModel();
        modelo.setRowCount(0);
        
        for (Cliente p : listaClientes.getClientes()){
            modelo.addRow(new Object[]{
                p.getNumero(), p.getNombre(), p.getTelefono(), p.getCorreo()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listaButton = new javax.swing.JButton();
        inventarioButton = new javax.swing.JButton();
        recepcionButton = new javax.swing.JButton();
        categoriasButton = new javax.swing.JButton();
        clientesButton = new javax.swing.JButton();
        paneles = new javax.swing.JPanel();
        listaPane = new javax.swing.JPanel();
        scrollpane = new javax.swing.JScrollPane();
        tablaLista = new javax.swing.JTable();
        paneBuscar = new javax.swing.JPanel();
        buscar = new javax.swing.JButton();
        buscarLabel = new javax.swing.JLabel();
        buscarField = new javax.swing.JTextField();
        refrescar = new javax.swing.JButton();
        paneBotones = new javax.swing.JPanel();
        agregar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        mostrarInfo = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        listaSub = new javax.swing.JLabel();
        inventarioPane = new javax.swing.JPanel();
        scrollpane1 = new javax.swing.JScrollPane();
        tablaInv = new javax.swing.JTable();
        paneBuscar1 = new javax.swing.JPanel();
        buscar1 = new javax.swing.JButton();
        buscarLabel1 = new javax.swing.JLabel();
        buscarField1 = new javax.swing.JTextField();
        refrescar1 = new javax.swing.JButton();
        invSub = new javax.swing.JLabel();
        recepcionPane = new javax.swing.JPanel();
        recepSub = new javax.swing.JLabel();
        scrollpane2 = new javax.swing.JScrollPane();
        tablaRecep = new javax.swing.JTable();
        paneBuscar2 = new javax.swing.JPanel();
        prodLabel = new javax.swing.JLabel();
        cantLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        prodCombo = new javax.swing.JComboBox<>();
        cantSpinner = new javax.swing.JSpinner();
        fechaField = new javax.swing.JFormattedTextField();
        agregarLista = new javax.swing.JButton();
        paneBotones1 = new javax.swing.JPanel();
        eliminar2 = new javax.swing.JButton();
        guardar2 = new javax.swing.JButton();
        categoriasPane = new javax.swing.JPanel();
        categSub = new javax.swing.JLabel();
        scrollpane3 = new javax.swing.JScrollPane();
        tablaCat = new javax.swing.JTable();
        paneBuscar3 = new javax.swing.JPanel();
        catLabel = new javax.swing.JLabel();
        agregar2 = new javax.swing.JButton();
        catField = new javax.swing.JTextField();
        eliminar3 = new javax.swing.JButton();
        clientesPane = new javax.swing.JPanel();
        recepSub1 = new javax.swing.JLabel();
        scrollpane4 = new javax.swing.JScrollPane();
        tablaClient = new javax.swing.JTable();
        paneBuscar4 = new javax.swing.JPanel();
        numLabel = new javax.swing.JLabel();
        nomLabel = new javax.swing.JLabel();
        telLabel = new javax.swing.JLabel();
        correoLabel = new javax.swing.JLabel();
        agregar3 = new javax.swing.JButton();
        numField = new javax.swing.JTextField();
        nomField = new javax.swing.JTextField();
        telField = new javax.swing.JTextField();
        correoField = new javax.swing.JTextField();
        paneBotones4 = new javax.swing.JPanel();
        eliminar5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 600));

        listaButton.setBackground(new java.awt.Color(50, 50, 50));
        listaButton.setForeground(new java.awt.Color(255, 255, 255));
        listaButton.setText("Lista");
        listaButton.setBorderPainted(false);
        listaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaButtonActionPerformed(evt);
            }
        });

        inventarioButton.setBackground(new java.awt.Color(50, 50, 50));
        inventarioButton.setForeground(new java.awt.Color(255, 255, 255));
        inventarioButton.setText("Inventario");
        inventarioButton.setBorderPainted(false);
        inventarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        inventarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioButtonActionPerformed(evt);
            }
        });

        recepcionButton.setBackground(new java.awt.Color(50, 50, 50));
        recepcionButton.setForeground(new java.awt.Color(255, 255, 255));
        recepcionButton.setText("Recepcion");
        recepcionButton.setBorderPainted(false);
        recepcionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        recepcionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepcionButtonActionPerformed(evt);
            }
        });

        categoriasButton.setBackground(new java.awt.Color(50, 50, 50));
        categoriasButton.setForeground(new java.awt.Color(255, 255, 255));
        categoriasButton.setText("Categorias");
        categoriasButton.setBorderPainted(false);
        categoriasButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        categoriasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriasButtonActionPerformed(evt);
            }
        });

        clientesButton.setBackground(new java.awt.Color(50, 50, 50));
        clientesButton.setForeground(new java.awt.Color(255, 255, 255));
        clientesButton.setText("Clientes");
        clientesButton.setBorderPainted(false);
        clientesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(categoriasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recepcionButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventarioButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(listaButton)
                .addGap(18, 18, 18)
                .addComponent(inventarioButton)
                .addGap(18, 18, 18)
                .addComponent(recepcionButton)
                .addGap(18, 18, 18)
                .addComponent(categoriasButton)
                .addGap(18, 18, 18)
                .addComponent(clientesButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneles.setLayout(new java.awt.CardLayout());

        listaPane.setBackground(new java.awt.Color(255, 255, 255));

        tablaLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Categoría", "Tipo", "Precio", "Stock"
            }
        ));
        scrollpane.setViewportView(tablaLista);

        paneBuscar.setBackground(new java.awt.Color(255, 255, 255));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        buscarLabel.setText("Buscar por ID: ");

        buscarField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFieldActionPerformed(evt);
            }
        });

        refrescar.setText("Refrescar");
        refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBuscarLayout = new javax.swing.GroupLayout(paneBuscar);
        paneBuscar.setLayout(paneBuscarLayout);
        paneBuscarLayout.setHorizontalGroup(
            paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscarLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(buscarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscar)
                .addGap(18, 18, 18)
                .addComponent(refrescar)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        paneBuscarLayout.setVerticalGroup(
            paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buscarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(refrescar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneBotones.setBackground(new java.awt.Color(255, 255, 255));

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        mostrarInfo.setText("Mostrar Info");
        mostrarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarInfoActionPerformed(evt);
            }
        });

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBotonesLayout = new javax.swing.GroupLayout(paneBotones);
        paneBotones.setLayout(paneBotonesLayout);
        paneBotonesLayout.setHorizontalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotonesLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(agregar)
                .addGap(31, 31, 31)
                .addComponent(modificar)
                .addGap(32, 32, 32)
                .addComponent(eliminar)
                .addGap(32, 32, 32)
                .addComponent(mostrarInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardar)
                .addGap(58, 58, 58))
        );
        paneBotonesLayout.setVerticalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotonesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(agregar)
                        .addComponent(modificar)
                        .addComponent(eliminar))
                    .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mostrarInfo)
                        .addComponent(guardar)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        listaSub.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        listaSub.setText("Lista de medicinas");

        javax.swing.GroupLayout listaPaneLayout = new javax.swing.GroupLayout(listaPane);
        listaPane.setLayout(listaPaneLayout);
        listaPaneLayout.setHorizontalGroup(
            listaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaPaneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(listaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaSub, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollpane))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        listaPaneLayout.setVerticalGroup(
            listaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaPaneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(listaSub)
                .addGap(18, 18, 18)
                .addComponent(paneBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        paneles.add(listaPane, "card3");

        inventarioPane.setBackground(new java.awt.Color(255, 255, 255));

        tablaInv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Stock", "Expirados", "Disponibles"
            }
        ));
        scrollpane1.setViewportView(tablaInv);
        if (tablaInv.getColumnModel().getColumnCount() > 0) {
            tablaInv.getColumnModel().getColumn(3).setHeaderValue("Expirados");
            tablaInv.getColumnModel().getColumn(4).setHeaderValue("Disponibles");
        }

        paneBuscar1.setBackground(new java.awt.Color(255, 255, 255));

        buscar1.setText("Buscar");
        buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar1ActionPerformed(evt);
            }
        });

        buscarLabel1.setText("Buscar por ID: ");

        buscarField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarField1ActionPerformed(evt);
            }
        });

        refrescar1.setText("Refrescar");
        refrescar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBuscar1Layout = new javax.swing.GroupLayout(paneBuscar1);
        paneBuscar1.setLayout(paneBuscar1Layout);
        paneBuscar1Layout.setHorizontalGroup(
            paneBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscar1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(buscarLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarField1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscar1)
                .addGap(18, 18, 18)
                .addComponent(refrescar1)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        paneBuscar1Layout.setVerticalGroup(
            paneBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscar1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(paneBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBuscar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buscarLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(refrescar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        invSub.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        invSub.setText("Inventario");

        javax.swing.GroupLayout inventarioPaneLayout = new javax.swing.GroupLayout(inventarioPane);
        inventarioPane.setLayout(inventarioPaneLayout);
        inventarioPaneLayout.setHorizontalGroup(
            inventarioPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventarioPaneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inventarioPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(invSub, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneBuscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollpane1))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        inventarioPaneLayout.setVerticalGroup(
            inventarioPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventarioPaneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(invSub)
                .addGap(18, 18, 18)
                .addComponent(paneBuscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollpane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        paneles.add(inventarioPane, "card2");

        recepcionPane.setBackground(new java.awt.Color(255, 255, 255));
        recepcionPane.setPreferredSize(new java.awt.Dimension(687, 643));

        recepSub.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        recepSub.setText("Manejar recepción");

        tablaRecep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Expiración", "Producto", "Cantidad"
            }
        ));
        scrollpane2.setViewportView(tablaRecep);

        paneBuscar2.setBackground(new java.awt.Color(255, 255, 255));

        prodLabel.setText("Producto: ");

        cantLabel.setText("Cantidad: ");

        fechaLabel.setText("Fecha de expiración: ");

        prodCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        prodCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodComboActionPerformed(evt);
            }
        });

        fechaField.setText("dd/mm/yyyy");
        fechaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaFieldActionPerformed(evt);
            }
        });

        agregarLista.setText("Agregar a lista");

        javax.swing.GroupLayout paneBuscar2Layout = new javax.swing.GroupLayout(paneBuscar2);
        paneBuscar2.setLayout(paneBuscar2Layout);
        paneBuscar2Layout.setHorizontalGroup(
            paneBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBuscar2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(paneBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodLabel)
                    .addComponent(prodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(paneBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantLabel)
                    .addComponent(cantSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(paneBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(agregarLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaField))
                .addGap(70, 70, 70))
        );
        paneBuscar2Layout.setVerticalGroup(
            paneBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscar2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(paneBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaLabel)
                    .addComponent(cantLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneBuscar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(agregarLista)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        paneBotones1.setBackground(new java.awt.Color(255, 255, 255));

        eliminar2.setText("Eliminar");
        eliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar2ActionPerformed(evt);
            }
        });

        guardar2.setText("Guardar");
        guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBotones1Layout = new javax.swing.GroupLayout(paneBotones1);
        paneBotones1.setLayout(paneBotones1Layout);
        paneBotones1Layout.setHorizontalGroup(
            paneBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBotones1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        paneBotones1Layout.setVerticalGroup(
            paneBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotones1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(paneBotones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar2)
                    .addComponent(eliminar2))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout recepcionPaneLayout = new javax.swing.GroupLayout(recepcionPane);
        recepcionPane.setLayout(recepcionPaneLayout);
        recepcionPaneLayout.setHorizontalGroup(
            recepcionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recepcionPaneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(recepcionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(recepSub, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneBuscar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollpane2)
                    .addComponent(paneBotones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        recepcionPaneLayout.setVerticalGroup(
            recepcionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recepcionPaneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(recepSub)
                .addGap(18, 18, 18)
                .addComponent(paneBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollpane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        paneles.add(recepcionPane, "card6");

        categoriasPane.setBackground(new java.awt.Color(255, 255, 255));
        categoriasPane.setPreferredSize(new java.awt.Dimension(687, 643));

        categSub.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        categSub.setText("Manejar categorías");

        tablaCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Categoría"
            }
        ));
        scrollpane3.setViewportView(tablaCat);

        paneBuscar3.setBackground(new java.awt.Color(255, 255, 255));

        catLabel.setText("Categoría: ");

        agregar2.setText("Agregar");
        agregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar2ActionPerformed(evt);
            }
        });

        eliminar3.setText("Eliminar");
        eliminar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBuscar3Layout = new javax.swing.GroupLayout(paneBuscar3);
        paneBuscar3.setLayout(paneBuscar3Layout);
        paneBuscar3Layout.setHorizontalGroup(
            paneBuscar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscar3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(paneBuscar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminar3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catLabel)
                    .addComponent(catField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        paneBuscar3Layout.setVerticalGroup(
            paneBuscar3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscar3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(catLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(catField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agregar2)
                .addGap(62, 62, 62)
                .addComponent(eliminar3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout categoriasPaneLayout = new javax.swing.GroupLayout(categoriasPane);
        categoriasPane.setLayout(categoriasPaneLayout);
        categoriasPaneLayout.setHorizontalGroup(
            categoriasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriasPaneLayout.createSequentialGroup()
                .addGroup(categoriasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(categoriasPaneLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(categSub, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(344, 344, 344))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, categoriasPaneLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(paneBuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(scrollpane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        categoriasPaneLayout.setVerticalGroup(
            categoriasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoriasPaneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(categSub)
                .addGap(18, 18, 18)
                .addGroup(categoriasPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollpane3, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(paneBuscar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        paneles.add(categoriasPane, "card4");

        clientesPane.setBackground(new java.awt.Color(255, 255, 255));
        clientesPane.setPreferredSize(new java.awt.Dimension(687, 643));

        recepSub1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        recepSub1.setText("Manejar clientes");

        tablaClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. Cliente", "Nombre", "Teléfono", "Correo"
            }
        ));
        scrollpane4.setViewportView(tablaClient);

        paneBuscar4.setBackground(new java.awt.Color(255, 255, 255));

        numLabel.setText("Número de Cliente: ");

        nomLabel.setText("Nombre: ");

        telLabel.setText("Teléfono: ");

        correoLabel.setText("Correo: ");

        agregar3.setText("Agregar");
        agregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBuscar4Layout = new javax.swing.GroupLayout(paneBuscar4);
        paneBuscar4.setLayout(paneBuscar4Layout);
        paneBuscar4Layout.setHorizontalGroup(
            paneBuscar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscar4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBuscar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numField)
                    .addComponent(numLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(paneBuscar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomField)
                    .addComponent(nomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(paneBuscar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(telField)
                    .addComponent(telLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paneBuscar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(correoField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(correoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(paneBuscar4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(agregar3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        paneBuscar4Layout.setVerticalGroup(
            paneBuscar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscar4Layout.createSequentialGroup()
                .addGroup(paneBuscar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBuscar4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(numLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneBuscar4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(paneBuscar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBuscar4Layout.createSequentialGroup()
                                .addComponent(nomLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneBuscar4Layout.createSequentialGroup()
                                .addComponent(telLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneBuscar4Layout.createSequentialGroup()
                                .addComponent(correoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(agregar3)
                .addGap(18, 18, 18))
        );

        paneBotones4.setBackground(new java.awt.Color(255, 255, 255));

        eliminar5.setText("Eliminar");
        eliminar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBotones4Layout = new javax.swing.GroupLayout(paneBotones4);
        paneBotones4.setLayout(paneBotones4Layout);
        paneBotones4Layout.setHorizontalGroup(
            paneBotones4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBotones4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(eliminar5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        paneBotones4Layout.setVerticalGroup(
            paneBotones4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotones4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eliminar5)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout clientesPaneLayout = new javax.swing.GroupLayout(clientesPane);
        clientesPane.setLayout(clientesPaneLayout);
        clientesPaneLayout.setHorizontalGroup(
            clientesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesPaneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(clientesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(recepSub1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneBuscar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollpane4, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addComponent(paneBotones4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        clientesPaneLayout.setVerticalGroup(
            clientesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientesPaneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(recepSub1)
                .addGap(18, 18, 18)
                .addComponent(paneBuscar4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollpane4, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paneBotones4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        paneles.add(clientesPane, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addComponent(paneles, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaButtonActionPerformed
        cardLayout.show(paneles, "listaPane");
        actualizarTabla();
    }//GEN-LAST:event_listaButtonActionPerformed

    private void inventarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioButtonActionPerformed
        cardLayout.show(paneles, "inventarioPane");
    }//GEN-LAST:event_inventarioButtonActionPerformed

    private void recepcionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepcionButtonActionPerformed
        cardLayout.show(paneles, "recepcionPane");
    }//GEN-LAST:event_recepcionButtonActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        if(buscarField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Escriba un ID para buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            try{
                int id = parseInt(buscarField.getText().trim());
                Producto p = inventario.buscarProducto(id);

                DefaultTableModel modelo = (DefaultTableModel) tablaLista.getModel();
                modelo.setRowCount(0);
                if (p != null){
                    modelo.addRow(new Object[]{
                        p.getId(), p.getNombre(), p.getCategoria(), p.getTipo(), p.getPrecio(), p.getStock()
                    });
                }else{
                    JOptionPane.showMessageDialog(this, "Producto no encontrado.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Ingrese un ID válido.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }finally{
                buscarField.setText("");
            }
        }  
    }//GEN-LAST:event_buscarActionPerformed

    private void buscarFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarFieldActionPerformed

    private void refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_refrescarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        VentanaAgregarProducto ventana = new VentanaAgregarProducto(inventario, this, manejoCategorias);
        ventana.setVisible(true);
    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        int fila = tablaLista.getSelectedRow();
        if(fila != -1){
            int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas eliminar este producto?",
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                int id = Integer.parseInt(tablaLista.getValueAt(fila, 0).toString());
                inventario.eliminarProducto(id);
                actualizarTabla();
                JOptionPane.showMessageDialog(null, "Producto eliminado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecciona una fila.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void mostrarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarInfoActionPerformed
        int fila = tablaLista.getSelectedRow();
        if(fila != -1){
            String mensaje = "Datos del producto:\n";
            for(int i=0; i<6; i++){
                mensaje = mensaje + tablaLista.getColumnName(i) + ": " + tablaLista.getValueAt(fila, i) + "\n";
            }
            JOptionPane.showMessageDialog(null, mensaje, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Selecciona una fila.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_mostrarInfoActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        inventario.guardarInventario(AdminPanel.this);
    }//GEN-LAST:event_guardarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        int fila = tablaLista.getSelectedRow();
        if (fila != -1) {
            int id = Integer.parseInt(tablaLista.getValueAt(fila, 0).toString());
            Producto producto = inventario.buscarProducto(id);
            if (producto != null) {
                new VentanaAgregarProducto(inventario, this, producto, manejoCategorias).setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecciona una fila.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void categoriasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriasButtonActionPerformed
        cardLayout.show(paneles, "categoriasPane");
        actualizarTablaCat();
    }//GEN-LAST:event_categoriasButtonActionPerformed

    private void clientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesButtonActionPerformed
        cardLayout.show(paneles, "clientesPane");
        actualizarTablaClient();
    }//GEN-LAST:event_clientesButtonActionPerformed

    private void buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscar1ActionPerformed

    private void buscarField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarField1ActionPerformed

    private void refrescar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refrescar1ActionPerformed

    private void prodComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodComboActionPerformed

    private void eliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar2ActionPerformed

    private void fechaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaFieldActionPerformed

    private void guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardar2ActionPerformed

    private void eliminar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar3ActionPerformed
        int fila = tablaCat.getSelectedRow();
        if(fila != -1){
            int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas eliminar esta categoria?",
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                String nombre = tablaCat.getValueAt(fila, 0).toString();
                manejoCategorias.eliminarCategoria(manejoCategorias.buscarCategoria(nombre));
                actualizarTablaCat();
                JOptionPane.showMessageDialog(null, "Categoria eliminada", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecciona una fila.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_eliminar3ActionPerformed

    private void agregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar3ActionPerformed
        try{
            int num = Integer.parseInt(numField.getText());
            String nom = nomField.getText();
            long tel = Long.parseLong(telField.getText());
            String correo = correoField.getText();
            
            String regex = "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@" + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(correo);
            if(!matcher.matches()){
                throw new Exception();
            }
            
            Cliente c = new Cliente(num, nom, tel, correo);
            listaClientes.agregarCliente(c);

            JOptionPane.showMessageDialog(this,"El cliente ha sido agregado","Mensaje", JOptionPane.INFORMATION_MESSAGE,null);
            if (this != null) {
                actualizarTablaClient();
            }
            numField.setText("");
            nomField.setText("");
            telField.setText("");
            correoField.setText("");
        }catch (Exception e){ 
            /* Si se produce algún tipo de error, se muestra un mensaje */
            JOptionPane.showMessageDialog(null,"Campo nulo o error en formato de numero", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
	}
    }//GEN-LAST:event_agregar3ActionPerformed

    private void agregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar2ActionPerformed
        try{
            Categoria c = new Categoria(catField.getText());
            manejoCategorias.agregarCategoria(c);

            JOptionPane.showMessageDialog(this,"La categoria ha sido agregada","Mensaje", JOptionPane.INFORMATION_MESSAGE,null);
            if (this != null) {
                actualizarTablaCat();
            }
            catField.setText("");
        }catch (Exception e){ 
            /* Si se produce algún tipo de error, se muestra un mensaje */
            JOptionPane.showMessageDialog(null,"Campo nulo o error en formato de numero", "Error", JOptionPane.ERROR_MESSAGE);
	}
    }//GEN-LAST:event_agregar2ActionPerformed

    private void eliminar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar5ActionPerformed
        int fila = tablaClient.getSelectedRow();
        if(fila != -1){
            int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas eliminar este cliente?",
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                int num = Integer.parseInt(tablaClient.getValueAt(fila, 0).toString());
                listaClientes.eliminarCliente(listaClientes.buscarCliente(num));
                actualizarTablaClient();
                JOptionPane.showMessageDialog(null, "Cliente eliminado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecciona una fila.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_eliminar5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton agregar2;
    private javax.swing.JButton agregar3;
    private javax.swing.JButton agregarLista;
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscar1;
    private javax.swing.JTextField buscarField;
    private javax.swing.JTextField buscarField1;
    private javax.swing.JLabel buscarLabel;
    private javax.swing.JLabel buscarLabel1;
    private javax.swing.JLabel cantLabel;
    private javax.swing.JSpinner cantSpinner;
    private javax.swing.JTextField catField;
    private javax.swing.JLabel catLabel;
    private javax.swing.JLabel categSub;
    private javax.swing.JButton categoriasButton;
    private javax.swing.JPanel categoriasPane;
    private javax.swing.JButton clientesButton;
    private javax.swing.JPanel clientesPane;
    private javax.swing.JTextField correoField;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton eliminar2;
    private javax.swing.JButton eliminar3;
    private javax.swing.JButton eliminar5;
    private javax.swing.JFormattedTextField fechaField;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JButton guardar;
    private javax.swing.JButton guardar2;
    private javax.swing.JLabel invSub;
    private javax.swing.JButton inventarioButton;
    private javax.swing.JPanel inventarioPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton listaButton;
    private javax.swing.JPanel listaPane;
    private javax.swing.JLabel listaSub;
    private javax.swing.JButton modificar;
    private javax.swing.JButton mostrarInfo;
    private javax.swing.JTextField nomField;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextField numField;
    private javax.swing.JLabel numLabel;
    private javax.swing.JPanel paneBotones;
    private javax.swing.JPanel paneBotones1;
    private javax.swing.JPanel paneBotones4;
    private javax.swing.JPanel paneBuscar;
    private javax.swing.JPanel paneBuscar1;
    private javax.swing.JPanel paneBuscar2;
    private javax.swing.JPanel paneBuscar3;
    private javax.swing.JPanel paneBuscar4;
    private javax.swing.JPanel paneles;
    private javax.swing.JComboBox<String> prodCombo;
    private javax.swing.JLabel prodLabel;
    private javax.swing.JLabel recepSub;
    private javax.swing.JLabel recepSub1;
    private javax.swing.JButton recepcionButton;
    private javax.swing.JPanel recepcionPane;
    private javax.swing.JButton refrescar;
    private javax.swing.JButton refrescar1;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JScrollPane scrollpane1;
    private javax.swing.JScrollPane scrollpane2;
    private javax.swing.JScrollPane scrollpane3;
    private javax.swing.JScrollPane scrollpane4;
    private javax.swing.JTable tablaCat;
    private javax.swing.JTable tablaClient;
    private javax.swing.JTable tablaInv;
    private javax.swing.JTable tablaLista;
    private javax.swing.JTable tablaRecep;
    private javax.swing.JTextField telField;
    private javax.swing.JLabel telLabel;
    // End of variables declaration//GEN-END:variables

}
