package com.mycompany.mavenproject1;
import java.awt.*;
import javax.swing.*;
import javax.swing.plaf.basic.BasicButtonUI;

public class MainFrame extends javax.swing.JFrame {
    private Inventario inventario;
    CardLayout cardLayout;
    public MainFrame() {
        initComponents();
        setResizable(false);
        setSize(1000,660);
        this.inventario = new Inventario();
        pane.setLayout(new CardLayout());

        pane.add(main, "main");
        AdminPanel adminPane = new AdminPanel(inventario);
        pane.add(adminPane, "adminPane");
        pane.add(vendedor, "vendedor");
        Component[] components = this.getContentPane().getComponents();
        for(Component component : components){
            if(component instanceof JButton){
                ((JButton) component).setUI(new BasicButtonUI());
                ((JButton) component).setFocusPainted(false);
            }
        }
        cardLayout = (CardLayout)(pane.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        adminBoton = new javax.swing.JButton();
        vendedorBoton = new javax.swing.JButton();
        admin = new javax.swing.JPanel();
        vendedor = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        regresar = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();
        acerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(989, 626));

        pane.setLayout(new java.awt.CardLayout());

        main.setBackground(new java.awt.Color(255, 255, 255));

        bienvenido.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        bienvenido.setText("¡Bienvenido!");

        adminBoton.setText("Administrador");
        adminBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBotonActionPerformed(evt);
            }
        });

        vendedorBoton.setText("Vendedor");
        vendedorBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendedorBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bienvenido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                        .addComponent(adminBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vendedorBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(bienvenido)
                .addGap(330, 330, 330)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminBoton)
                    .addComponent(vendedorBoton))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pane.add(main, "card2");

        javax.swing.GroupLayout adminLayout = new javax.swing.GroupLayout(admin);
        admin.setLayout(adminLayout);
        adminLayout.setHorizontalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
        );
        adminLayout.setVerticalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );

        pane.add(admin, "card3");

        javax.swing.GroupLayout vendedorLayout = new javax.swing.GroupLayout(vendedor);
        vendedor.setLayout(vendedorLayout);
        vendedorLayout.setHorizontalGroup(
            vendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
        );
        vendedorLayout.setVerticalGroup(
            vendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );

        pane.add(vendedor, "card4");

        menu.setText("Menú");

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        menu.add(regresar);

        menuBar.add(menu);

        ayuda.setText("Ayuda");
        ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaActionPerformed(evt);
            }
        });

        acerca.setText("Acerca de");
        acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaActionPerformed(evt);
            }
        });
        ayuda.add(acerca);

        menuBar.add(ayuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        cardLayout.show(pane, "main");
    }//GEN-LAST:event_regresarActionPerformed

    private void adminBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBotonActionPerformed
        String usuario = "Admin";
        String contrasena = "admin321";
        
        JTextField userField = new JTextField();
        JTextField passwordField = new JTextField();
        JPanel panelIngreso = new JPanel(new GridLayout(4, 1));
        panelIngreso.add(new JLabel("Usuario:\n"));
        panelIngreso.add(userField);
        panelIngreso.add(new JLabel("Contraseña:\n"));
        panelIngreso.add(passwordField);
        int obtener = JOptionPane.showConfirmDialog(null, panelIngreso, "Ingreso administrador",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        if(obtener == JOptionPane.OK_OPTION){
            String user = userField.getText();
            String password = passwordField.getText();
    
            if (user != null && password != null){
                if(user.equals(usuario) && password.equals(contrasena)){
                    cardLayout.show(pane, "adminPane");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Ingreso incorrecto.");
                }
            }
        }   
    }//GEN-LAST:event_adminBotonActionPerformed

    private void vendedorBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendedorBotonActionPerformed
        cardLayout.show(pane, "vendedor");
    }//GEN-LAST:event_vendedorBotonActionPerformed

    private void ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaActionPerformed
        //
    }//GEN-LAST:event_ayudaActionPerformed
    
    private void acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaActionPerformed
        JOptionPane.showMessageDialog(null, "Aplicación creada por:\nAguirre Grajeda José Álvaro\nEscobar Hernández Natalia\nEspinoza López Roberto");
    }//GEN-LAST:event_acercaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acerca;
    private javax.swing.JPanel admin;
    private javax.swing.JButton adminBoton;
    private javax.swing.JMenu ayuda;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JPanel main;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel pane;
    private javax.swing.JMenuItem regresar;
    private javax.swing.JPanel vendedor;
    private javax.swing.JButton vendedorBoton;
    // End of variables declaration//GEN-END:variables
}
