package com.mycompany.mavenproject1;
import java.awt.*;
import javax.swing.*;
import javax.swing.plaf.basic.BasicButtonUI;

public class NewJFrame extends javax.swing.JFrame {

    CardLayout cardLayout;
    public NewJFrame() {
        initComponents();
        paneles.setLayout(new java.awt.CardLayout());

        paneles.add(productosPane, "productosPane");
        paneles.add(inventarioPane, "inventarioPane");
        paneles.add(categoriaPane, "categoriaPane");
        Component[] components = this.getContentPane().getComponents();
        for(Component component : components){
            if(component instanceof JButton){
                ((JButton) component).setUI(new BasicButtonUI());
                ((JButton) component).setFocusPainted(false);
            }
        }
        cardLayout = (CardLayout)(paneles.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inventarioButton = new javax.swing.JButton();
        productosButton = new javax.swing.JButton();
        categoriaButton = new javax.swing.JButton();
        paneles = new javax.swing.JPanel();
        inventarioPane = new javax.swing.JPanel();
        scrollpane = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        paneBuscar = new javax.swing.JPanel();
        buscar = new javax.swing.JButton();
        buscarLabel = new javax.swing.JLabel();
        buscarField = new javax.swing.JTextField();
        refrescar = new javax.swing.JButton();
        paneBotones = new javax.swing.JPanel();
        agregar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        mostrarInfo = new javax.swing.JButton();
        subtitulo = new javax.swing.JLabel();
        categoriaPane = new javax.swing.JPanel();
        productosPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 600));

        inventarioButton.setBackground(new java.awt.Color(50, 50, 50));
        inventarioButton.setForeground(new java.awt.Color(255, 255, 255));
        inventarioButton.setText("Inventario");
        inventarioButton.setBorderPainted(false);
        inventarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        inventarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioButtonActionPerformed(evt);
            }
        });

        productosButton.setBackground(new java.awt.Color(50, 50, 50));
        productosButton.setForeground(new java.awt.Color(255, 255, 255));
        productosButton.setText("Productos");
        productosButton.setBorderPainted(false);
        productosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        productosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosButtonActionPerformed(evt);
            }
        });

        categoriaButton.setBackground(new java.awt.Color(50, 50, 50));
        categoriaButton.setForeground(new java.awt.Color(255, 255, 255));
        categoriaButton.setText("Categorías");
        categoriaButton.setBorderPainted(false);
        categoriaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        categoriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoriaButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inventarioButton)
                            .addComponent(productosButton))))
                .addGap(0, 83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 260, Short.MAX_VALUE)
                .addComponent(inventarioButton)
                .addGap(20, 20, 20)
                .addComponent(productosButton)
                .addGap(20, 20, 20)
                .addComponent(categoriaButton)
                .addGap(0, 261, Short.MAX_VALUE))
        );

        paneles.setLayout(new java.awt.CardLayout());

        inventarioPane.setBackground(new java.awt.Color(255, 255, 255));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Categoría", "Tipo", "Precio", "Cantidad"
            }
        ));
        scrollpane.setViewportView(tabla);

        paneBuscar.setBackground(new java.awt.Color(255, 255, 255));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        buscarLabel.setText("Buscar por ID: ");

        buscarField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFieldActionPerformed(evt);
            }
        });

        refrescar.setText("Refrescar");
        refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBuscarLayout = new javax.swing.GroupLayout(paneBuscar);
        paneBuscar.setLayout(paneBuscarLayout);
        paneBuscarLayout.setHorizontalGroup(
            paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscarLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(buscarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscar)
                .addGap(18, 18, 18)
                .addComponent(refrescar)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        paneBuscarLayout.setVerticalGroup(
            paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buscarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(refrescar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneBotones.setBackground(new java.awt.Color(255, 255, 255));

        agregar.setText("Agregar");

        modificar.setText("Modificar");

        eliminar.setText("Eliminar");

        mostrarInfo.setText("Mostrar Info");

        javax.swing.GroupLayout paneBotonesLayout = new javax.swing.GroupLayout(paneBotones);
        paneBotones.setLayout(paneBotonesLayout);
        paneBotonesLayout.setHorizontalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotonesLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(agregar)
                .addGap(31, 31, 31)
                .addComponent(modificar)
                .addGap(32, 32, 32)
                .addComponent(eliminar)
                .addGap(32, 32, 32)
                .addComponent(mostrarInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneBotonesLayout.setVerticalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotonesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(agregar)
                        .addComponent(modificar)
                        .addComponent(eliminar))
                    .addComponent(mostrarInfo))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        subtitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        subtitulo.setText("Administrar Inventario");

        javax.swing.GroupLayout inventarioPaneLayout = new javax.swing.GroupLayout(inventarioPane);
        inventarioPane.setLayout(inventarioPaneLayout);
        inventarioPaneLayout.setHorizontalGroup(
            inventarioPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventarioPaneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(inventarioPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollpane)
                    .addComponent(paneBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        inventarioPaneLayout.setVerticalGroup(
            inventarioPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventarioPaneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(subtitulo)
                .addGap(18, 18, 18)
                .addComponent(paneBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        paneles.add(inventarioPane, "card3");

        categoriaPane.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout categoriaPaneLayout = new javax.swing.GroupLayout(categoriaPane);
        categoriaPane.setLayout(categoriaPaneLayout);
        categoriaPaneLayout.setHorizontalGroup(
            categoriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
        categoriaPaneLayout.setVerticalGroup(
            categoriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        paneles.add(categoriaPane, "card4");

        productosPane.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout productosPaneLayout = new javax.swing.GroupLayout(productosPane);
        productosPane.setLayout(productosPaneLayout);
        productosPaneLayout.setHorizontalGroup(
            productosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
        productosPaneLayout.setVerticalGroup(
            productosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        paneles.add(productosPane, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 665, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 251, Short.MAX_VALUE)
                    .addComponent(paneles, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(paneles, javax.swing.GroupLayout.PREFERRED_SIZE, 630, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosButtonActionPerformed
        cardLayout.show(paneles, "productosPane");
    }//GEN-LAST:event_productosButtonActionPerformed

    private void inventarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioButtonActionPerformed
        cardLayout.show(paneles, "inventarioPane");
    }//GEN-LAST:event_inventarioButtonActionPerformed

    private void categoriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaButtonActionPerformed
        cardLayout.show(paneles, "categoriaPane");
    }//GEN-LAST:event_categoriaButtonActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    private void buscarFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarFieldActionPerformed

    private void refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refrescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField buscarField;
    private javax.swing.JLabel buscarLabel;
    private javax.swing.JButton categoriaButton;
    private javax.swing.JPanel categoriaPane;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton inventarioButton;
    private javax.swing.JPanel inventarioPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificar;
    private javax.swing.JButton mostrarInfo;
    private javax.swing.JPanel paneBotones;
    private javax.swing.JPanel paneBuscar;
    private javax.swing.JPanel paneles;
    private javax.swing.JButton productosButton;
    private javax.swing.JPanel productosPane;
    private javax.swing.JButton refrescar;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
