package com.mycompany.mavenproject1;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VentanaProducto extends javax.swing.JFrame{
    private Inventario inventario;
    private DatosDelSistema datosSistema;
    
    public VentanaProducto(Inventario inventario, DatosDelSistema datosSistema){
        initComponents();
        this.inventario = inventario;
        this.datosSistema = datosSistema;
        setResizable(false);
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        actualizarTabla();
    }
    
    public void actualizarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) tablaLista.getModel();
        modelo.setRowCount(0);
        
        for (Producto p : inventario.getLista()){
            modelo.addRow(new Object[]{
                p.getId(), p.getNombre(), p.getCategoria(), p.getTipo(), p.getPrecio()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaPane = new javax.swing.JPanel();
        sub = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tablaLista = new javax.swing.JTable();
        agregar = new javax.swing.JButton();
        nomLabel = new javax.swing.JLabel();
        nomField = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        refrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaPane.setBackground(new java.awt.Color(255, 255, 255));
        listaPane.setPreferredSize(new java.awt.Dimension(687, 643));

        sub.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        sub.setText("Buscar productos");

        tablaLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Categoría", "Tipo", "Precio"
            }
        ));
        scrollPane.setViewportView(tablaLista);

        agregar.setText("Agregar a venta");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        nomLabel.setText("Buscar por nombre:");

        nomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomFieldActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        refrescar.setText("Refrescar");
        refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listaPaneLayout = new javax.swing.GroupLayout(listaPane);
        listaPane.setLayout(listaPaneLayout);
        listaPaneLayout.setHorizontalGroup(
            listaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaPaneLayout.createSequentialGroup()
                .addGroup(listaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listaPaneLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(listaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(listaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(listaPaneLayout.createSequentialGroup()
                                    .addComponent(nomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nomField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(55, 55, 55)
                                    .addComponent(buscar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(refrescar))
                                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(listaPaneLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        listaPaneLayout.setVerticalGroup(
            listaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaPaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(sub)
                .addGap(18, 18, 18)
                .addGroup(listaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomLabel)
                    .addComponent(nomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar)
                    .addComponent(refrescar))
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agregar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(listaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(listaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        int fila = tablaLista.getSelectedRow();
        if(fila != -1){
            String id = tablaLista.getValueAt(fila, 0).toString();
            datosSistema.setTxtProducto(id);
            JOptionPane.showMessageDialog(null, "Producto agregado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Selecciona una fila.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String nom = nomField.getText().trim();
        Producto producto = null;
        if(nomField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Escriba un nombre para buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            try{
                ArrayList<Producto> lista = inventario.getLista();
                for(Producto p: lista){
                    if(nom.equals(p.getNombre())){
                        int id = p.getId();
                        producto = inventario.buscarProducto(id);
                        break;
                    }
                }

                DefaultTableModel modelo = (DefaultTableModel) tablaLista.getModel();
                modelo.setRowCount(0);
                if (producto != null){
                    modelo.addRow(new Object[]{
                        producto.getId(), producto.getNombre(), producto.getCategoria(), producto.getTipo(), producto.getPrecio()
                    });
                }else{
                    JOptionPane.showMessageDialog(this, "Producto no encontrado.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Ingrese un nombre válido.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }finally{
                nomField.setText("");
            }
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_refrescarActionPerformed

    private void nomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscar;
    private javax.swing.JPanel listaPane;
    private javax.swing.JTextField nomField;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JButton refrescar;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel sub;
    private javax.swing.JTable tablaLista;
    // End of variables declaration//GEN-END:variables
}
